### ISSUE TITLE
I would like to figure out how to create an apk 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#27]
Just for grins, I decided to try VoterMate on my Android phone. It works like a charm! So much so that I now wonder whether a phone is a better size for this than a tablet. 
It turns out that I have half a dozen old Tracfone BLU phones with GPS chips. I would like to install VoterMate on these and I think that an apk is a more efficient way to install this on multiple devices

**Comment by DaleStan** [comment]
The apk should be in your VoterMate\bin\Debug\net8.0-android or VoterMate\bin\Release\net8.0-android folders, once you use the run or debug buttons to run it (the debug or release builds) on an attached device.

The release version is significantly smaller (36 MB vs 150 MB) but does not appear to be otherwise better.

**Comment by KenStanley** [comment]
Ah I will try that

**Comment by KenStanley** [comment]
That worked. At least as soon as I undid all the garbage that I did to try the chatGpt approach.
