### ISSUE TITLE
Could we allow the organizer (aka Ken) to assign a turf number to a given phone?

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#36]
Right now, I believe that the only way that I can control which houses show up on the phone is to change the canvass tab and create a new apk. 
I am fine with creating a new apk daily, but it would be inefficient to create a new apk for each canvasser. 
Could we add turf assignments to the schema, either as a separate tab or as a column in the canvass tab AND allow me to choose the turf on a startup page?

**Comment by DaleStan** [comment]
I could allow importing a file to replace the data that currently comes from the canvass tab, or I could read a new column from canvass that assigns each mobilizer to a particular turf.

**Comment by KenStanley** [comment]
Either of these woks for me. If you have implemented something already, or have started in that direction, let me know which you chose. If not, importing a file is probably slightly easier for me asI can change files a bit easier than I can recreate a .apk file though either works.

**Comment by DaleStan** [comment]
To make it easier for me to travelling-salesman the turfs in the future, I'm going to read a turf ID[^1] from column H of canvass, and then use that to write files that you can import later.

[^1]: This needs to be a valid filename, but is otherwise immaterial. I'm just using the numbers 1-16 for testing.

**Comment by DaleStan** [comment]
The turf files are generated in the Turf Files folder as part of a standard build, and can be generated out-of-band by running `VoterMate.BuildDatabase.exe path/to/excel/file.xlsx`.

If your working directory is outside the VoterMate repo, the Turf Files folder will appear in your working directory, instead of in the same folder as the solution file.
