### ISSUE TITLE
 Housemates should show up at the top of the list of voters shown to mobilizers

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#45]
The housemates list includes friends that mobilizers have identified in previous election cycles making housemates in incomplete term. 
Zonei McCowan OH0012699770, shows up 1,350 times in the housemates file, representing 685 connection (since it is symmetric) Yet when I showed Zonie her list, she did not recognize many people. I have not chased this down.

**Comment by DaleStan** [comment]
The distance scoring was backward (negative points for more than 1/2 mile away instead of positive for less) and the housemates score didn't work at all.

But even after fixing those, the scores might be arranged incorrectly, or she might just be in an unfortunate location. Most of her top 10 are are housemates, but the people getting 15+ points for being within 1/8 mile take up the next two-thirds of the first page.

The current scores are
- 20 at zero miles, down to 0 at 1/2 mile or more
- 10 for being housemates and/or previously identified
- 5 for being former classmates
- -100 for being displayed before

I picked those pretty arbitrarily; do you want to adjust them?

**Comment by KenStanley** [comment]
To me, the ideal would be


   - 20 * rand_between (0.2 and 1.0) for being housemates and/or previously
   identified

The idea here is to maximize the chance that they will fiind someone in the
first page, even if either the housemates or the address is bogus or
useless. Sometimes we are talking to someone at the household who is
not the named individual, in which case the housuemates list will be bogus
but the address may be useful.Sometimes people have no connection to their
neighborhood. And there are likely other reasons for one or the other to be
useless.


he/him
440 240 4945
Twitter <https://twitter.com/KS_Stanley> LinkedIn
<https://www.linkedin.com/in/ken-stanley-695874b/> Blog
<https://kendallstanley.wordpress.com/blog>
